### ISSUE TITLE
[Feature Request] - Wildcard support?

### ISSUE THREAD

**Issue by aburt2** [bboettcher3/mappersession#4]
Would it be possible for mappersession's JSON format to support wildcards for both sources and destinations? 

This would help for sharing mapping files between performers using the same instruments with different IDs (ie: T-Stick, torquetuner).

Examples:
`
"sources": [
    "bloop*.1/out1"
]
`
`
"destinations": [
    "beep*.1/drywet"
],
`

**Comment by malloch** [comment]
Hi @aburt2 this is already a feature of mappersession! When you load a mapping file by default it will match signal names regardless of the device name. If you wish to address specific devices you can pass in a `device_map` argument (to `load()` or `load_json()`) that specifies correspondences between devices mentioned in the file/json and devices that are actually active on the network.

**Comment by aburt2** [comment]
thank you Joe

**Comment by malloch** [comment]
I updated the documentation to provide some information on this feature...
